### ISSUE TITLE
Difference in rotation loss between this repo and the paper.

### ISSUE THREAD

**Issue by jubelsM** [nianticlabs/marepo#1]
Hi, in the paper (eq 6). it is stated the rotation loss is L1 for both the rotation and translation, in the loss.py the PoseLossMapFree/PoseLossMapFree_C2F uses angular loss.
Which loss should I use when trying to reproduce the results of fine-tuning on a single scene?

**Comment by tcavallari** [comment]
Hi, thank you for raising this issue.

We used the rotation loss from the MapFree paper (Arnold et al., "Map-free visual relocalization: Metric pose relative to a single image") which minimizes the angular error between the two rotation matrices. The formula should indeed look like this (with a slight abuse of notation): ![image](https://github.com/nianticlabs/marepo/assets/2661430/46015e21-41f9-4dda-987f-a0a31ea19914)


The version in the code is correct, you should be able to reproduce the fine tuning results with the scripts provided in the repository.
