### ISSUE TITLE
how to use

### ISSUE THREAD

**Issue by xinyeDai** [nianticlabs/marepo#2]
How to use this after I download the datasets.

**Comment by tcavallari** [comment]
Hello, the main [`README`](https://github.com/nianticlabs/marepo/blob/main/README.md) file contains instructions on how to evaluate the pretrained marepo models (to replicate the results from the paper) or retrain a new marepo network from scratch.

For example, to evaluate the existing models on the various datasets: https://github.com/nianticlabs/marepo?tab=readme-ov-file#marepo-evaluation

Please let us know if you have further questions.

**Comment by qinhaijian23** [comment]
> Hello, the main [`README`](https://github.com/nianticlabs/marepo/blob/main/README.md) file contains instructions on how to evaluate the pretrained marepo models (to replicate the results from the paper) or retrain a new marepo network from scratch.
> 
> For example, to evaluate the existing models on the various datasets: https://github.com/nianticlabs/marepo?tab=readme-ov-file#marepo-evaluation
> 
> Please let us know if you have further questions.

Hello, if I want to use your method to test my own dataset or RIO10 dataset, how can I replace your dataset with my own for testing?

**Comment by tcavallari** [comment]
Hi, to test on a different dataset you would have to create your own Dataset class.

You can look at [`dataset.py`](https://github.com/nianticlabs/marepo/blob/main/dataset.py) for details on the interface of the `__getitem__` call (as usual for PyTorch datasets). Once you have implemented the new dataset class, then you need to update the [testing script](https://github.com/nianticlabs/marepo/blob/main/test_marepo.py) to actually use it, then you can call it from a bash script, like the one we used to run the tests on the 7Scenes dataset, [here](https://github.com/nianticlabs/marepo/blob/main/scripts/test_7scenes.sh).
