### ISSUE TITLE
Unable to reproduce finetune results

### ISSUE THREAD

**Issue by jubelsM** [nianticlabs/marepo#3]
Hi,
When I use the conda env given in this repo and the script you supplied for fine-tuning the model, I get worse results than the original model on the Wayspots dataset.
I've created the dataset using preprocess_scripts/create_wayspots_testset.sh and train it using scripts/train_marepo_s_wayspots.sh with a minor change of removing the CUDA_VISIBLE_DEVICES parameter.

What do you think might be my problem?

**Comment by ebrach** [comment]
Hi Yuval,

sorry to hear you are facing issues. What results do you get?

Best,
Eric

**Comment by jubelsM** [comment]
|       Scene      | (10cm/5°)/(0.5m/5°) |
|------------------|---------------------|
| Bears            | 76.81/95.17         |
| Cubes            | 60.00/96.70         |
| Inscription      | 29.73/71.53         |
| Lawn             | 19.52/39.72         |
| Map              | 49.30/88.47         |
| Squarebench      | 68.11/100.00        |
| Statue           | 0.00/0.00           |
| Tendrils         | 12.22/33.91         |
| Therock          | 100.00/100.00       |
| Wintersign       | 0.00/1.21           |
| Average          | 41.51/62.67         |

**Comment by tcavallari** [comment]
Just to confirm your environment and data is setup correctly, can you run the evaluation using the pretrained fine-tuned models [we provide in the readme file](https://github.com/nianticlabs/marepo?tab=readme-ov-file#pre-trained-models)?

**Comment by jubelsM** [comment]
HI, these are the results I got with the released weights, which are almost identical to the ones in the paper
|       Scene      | (10cm/5°)/(0.5m/5°) |
|-----------------|---------------------|
| Bears            | 80.52/99.31         |
| Cubes            | 72.00/96.87         |
| Inscription      | 37.30/73.87         |
| Lawn             | 34.20/41.28         |
| Map              | 55.07/87.67         |
| Squarebench      | 70.71/100.00        |
| Statue           | 0.00/0.00           |
| Tendrils         | 29.26/34.94         |
| Therock          | 99.83/100.00       |
| Wintersign       | 0.00/0.34           |
| Average          | 47.89/63.43         |

**Comment by tcavallari** [comment]
Thanks for confirming that the pretrained fine-tuned weights produce the correct results.

We'll try to investigate what's going on, please bear with us.

**Comment by tcavallari** [comment]
Hi @jubelsM, thanks for your patience.

We found an issue with the preprocessing code that we released in this repository and caused the low finetuning performance.
This has been fixed in #5, the results with that change are actually slightly better on average than the numbers we had in the paper.

You can pull the repo and rerun the preprocessing/fine tuning scripts, and it should work fine now.
