### ISSUE TITLE
Code available for windows?

### ISSUE THREAD

**Issue by RebekkaBaertheleTHWS** [nianticlabs/marepo#7]
Is there a plan to make the code work on windows too?

I would like to use marepo in my masters thesis but I'm limited to Windows in my institution:(

**Comment by tcavallari** [comment]
Hi,

Thank you for your interest. Unfortunately we have no plans to support Windows.

You may try using WSL (Windows Subsystem for Linux). Note that we haven't tested with it so, while it should work in principle, we don't know for sure.

Feel free to reopen in case you have follow up questions.
